services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: mangara
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - db
    restart: unless-stopped
  amigoscode-api:
    container_name: amigoscode-api
    image: mangara2023/amigoscode-api
    environment:
       SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
    ports:
      - "8088:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped
#    command:
#      - --spring.datasource.url=jdbc:postgresql://db:5432/customer

networks:
 db:
  driver: bridge

volumes:
  db: